language: node_js
node_js: node
services: postgresql
env:
- NODE_ENV=test
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- npm install -g gulp-cli
- gulp compile
- npm run create-mock-data
after_script:
- npm run drop-all
